const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');
const readline = require('readline');

const askQuestion = (query) => {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    });

    return new Promise(resolve => {
        rl.question(query, (answer) => {
            rl.close();
            resolve(answer);
        });
    });
};

async function setupCookie() {
    console.log("=== Rawpixel Session Cookie Setup ===\n");
    console.log("This will:");
    console.log("  1. Open a browser window");
    console.log("  2. Navigate to Rawpixel login page");
    console.log("  3. Wait for you to log in");
    console.log("  4. Extract your session cookie");
    console.log("  5. Save it to .env file\n");

    const ready = await askQuestion("Ready to continue? (y/n): ");

    if (ready.toLowerCase() !== 'y') {
        console.log("Setup cancelled.");
        process.exit(0);
    }

    console.log("\nLaunching browser...\n");

    const browser = await chromium.launch({
        headless: false  // Show browser so user can log in
    });

    const context = await browser.newContext();
    const page = await context.newPage();

    try {
        // Navigate to login page
        await page.goto('https://www.rawpixel.com/user/login');

        console.log("📱 Browser opened!");
        console.log("\nPlease log in to Rawpixel in the browser window...");
        console.log("After logging in successfully, return here and press Enter.\n");

        // Wait for user to confirm they've logged in
        await askQuestion("Press Enter after you've logged in: ");

        console.log("\n🔍 Extracting session cookie...");

        // Get all cookies
        const cookies = await context.cookies();

        // Find the SSESS cookie (Drupal session cookie used by Rawpixel)
        const sessionCookie = cookies.find(c => c.name.startsWith('SSESS'));

        if (!sessionCookie) {
            console.log("\n❌ ERROR: Could not find session cookie!");
            console.log("\nPossible reasons:");
            console.log("  • You're not logged in yet");
            console.log("  • Login failed");
            console.log("  • Rawpixel changed their cookie format\n");
            console.log("Please try again and make sure you're fully logged in.\n");
            await browser.close();
            process.exit(1);
        }

        console.log(`✓ Found session cookie: ${sessionCookie.name}\n`);

        // Format the cookie as name=value
        const cookieString = `${sessionCookie.name}=${sessionCookie.value}`;

        // Check if .env exists
        const envPath = path.join(__dirname, '.env');
        let envContent = '';

        if (fs.existsSync(envPath)) {
            // Read existing .env file
            envContent = fs.readFileSync(envPath, 'utf8');

            // Check if RAWPIXEL_SESSION_COOKIE already exists
            if (envContent.includes('RAWPIXEL_SESSION_COOKIE=')) {
                // Replace existing cookie
                envContent = envContent.replace(
                    /RAWPIXEL_SESSION_COOKIE=.*/,
                    `RAWPIXEL_SESSION_COOKIE=${cookieString}`
                );
                console.log("📝 Updated existing .env file");
            } else {
                // Append to existing file
                envContent += `\nRAWPIXEL_SESSION_COOKIE=${cookieString}\n`;
                console.log("📝 Added cookie to existing .env file");
            }
        } else {
            // Create new .env file from template
            envContent = `# Rawpixel Session Cookie
# Auto-generated by setup-cookie.js

RAWPIXEL_SESSION_COOKIE=${cookieString}
`;
            console.log("📝 Created new .env file");
        }

        // Write to .env file
        fs.writeFileSync(envPath, envContent);

        console.log("\n✅ Success! Session cookie saved to .env\n");
        console.log("You can now run the downloader with:");
        console.log("  npm start\n");

        await browser.close();

    } catch (err) {
        console.error("\n❌ Error:", err.message);
        await browser.close();
        process.exit(1);
    }
}

setupCookie();
